# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # pull_request:
  #   branches: []

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./app

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-18.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout git project
        uses: actions/checkout@v2
      - name: Setup node dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - name: Generate static build
        run: npm run generate
      - name: Deploy build via scp
        uses: appleboy/scp-action@v0.1.1
        with:
          username: ${{ secrets.DREAMHOST_DANPEAVEYCOM_USERNAME }}
          key: ${{ secrets.DREAMHOST_DANPEAVEYCOM_KEY }}
          host: ${{ secrets.DREAMHOST_DANPEAVEYCOM_HOST }}
          port: ${{ secrets.DREAMHOST_DANPEAVEYCOM_PORT }}
          source: ./app/dist/*
          target: /home/${{ secrets.DREAMHOST_DANPEAVEYCOM_USERNAME }}/danpeavey.com/public
          strip_components: 2
          rm: true
