# This is a basic workflow to help you get started with Actions

name: 🚀 Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: []

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout git project
        uses: actions/checkout@v4
      - name: Setup node dependencies
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Generate static build
        run: pnpm build
      - name: Deploy to server
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -Pavzr --delete
          path: dist/*
          remote_path: /home/${{ secrets.DREAMHOST_DANPEAVEYCOM_USERNAME }}/danpeavey.com/public
          remote_host: ${{ secrets.DREAMHOST_DANPEAVEYCOM_HOST }}
          remote_user: ${{ secrets.DREAMHOST_DANPEAVEYCOM_USERNAME }}
          remote_port: ${{ secrets.DREAMHOST_DANPEAVEYCOM_PORT }}
          remote_key: ${{ secrets.DREAMHOST_DANPEAVEYCOM_KEY }}
          remote_key_pass: ${{ secrets.DREAMHOST_DANPEAVEYCOM_PASS }}
